apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lobstertank.fullname" . }}-secret
  labels:
    {{- include "lobstertank.labels" . | nindent 4 }}
type: Opaque
data:
  LT_AUTH_TOKEN_SECRET: {{ .Values.secrets.authTokenSecret | b64enc | quote }}
  LT_SECRETS_ENCRYPTION_KEY: {{ .Values.secrets.secretsEncryptionKey | b64enc | quote }}
  {{- if and (eq .Values.config.secretsProvider "vault") (not .Values.vault.existingSecret) }}
  LT_SECRETS_VAULT_TOKEN: {{ .Values.vault.token | b64enc | quote }}
  {{- end }}
